### ISSUE TITLE
Missing locales in /etc/locale.gen

### ISSUE THREAD

**Issue by sudoforge** [terencewestphal/docker-archlinux#1]
Hey there. Thanks _so much_ for the image - I'm using it over on the [develop branch][0] of [Archer][1] for testing Ansible roles with Molecule.

I'm sure you're aware of this, but the image here only ships with `en_US.UTF-8` in `/etc/locale.gen`. Are you planning on refactoring this?

It breaks the `locale_gen` Ansible module, which doesn't add specified locales to the gen file (but it probably should; I'm going to open an issue for that in the ansible repo).

[0]: https://github.com/bddenhartog/archer/tree/develop
[1]: https://github.com/bddenhartog/archer

**Comment by terencewestphal** [comment]
Hi @sudoforge, thanks for your interest in this project.

This project's file structure is ment to be overridden when needed. You could fork it and add the missing locales in `bootstrap/etc/locale.gen` or remove the line `root.x86_64/etc/locale.gen` from `exclude`. The thing with this images is that I need to provide a default `LANG` so I picked to only obvious choice `en_US.UTF-8`. However this might not work for everyone. 

I see 3 ways how I could deal with this:
1. Add all locales to locale.gen and uncomment 1 `LANG` during installation.
2. Add an optional `LANG` parameter as a `docker build` argument
3. Leave it as it is but add better documentation on how to modify the docker image

Let me know what would solve your issue.

**Comment by sudoforge** [comment]
Hey there! Thanks for the reply.

As I mentioned, my use case for this image is as a container for testing [Archer][0] (you can see this on the [`develop`][1] branch currently), a set of Ansible playbooks meant to automate the provisioning of an Arch Linux workstation.

> This project's file structure is ment to be overridden when needed. You could fork it and add the missing locales in bootstrap/etc/locale.gen or remove the line root.x86_64/etc/locale.gen from exclude.

The "workaround" for my issue was simply adding the correct locale line to `/etc/locale.gen` after starting the container, and before attempting to generate locales. Admittedly, on the first use of this image, I didn't actually attach to it and inspect it -- I simply ran an Ansible task that took a list of locales, ensured they were uncommented in `/etc/locale.gen`, and attempted to generate locales. This errored, of course, because the "other" locales didn't exist in the genfile at all!

It was pretty simple to figure out a workaround, and my inital approach wasn't the most fail-safe anyway, but I decided to open this issue because your image differs from a base Arch Linux installation (perhaps neccessarily). In a base Arch Linux installation, the user is provided the full list of locales at `/etc/locale.gen`, and must uncomment one.

For the purposes of this image, I believe it should behave accordingly - that is, include all of the locales, and simply uncomment the desired default. Whether or not their is additional functionality provided to the user so that they can more easily control the locales present in a running container is, in my opinion, out of the scope of the reason this issue was created. 

[0]: https://github.com/sudoforge/archer
[1]: https://github.com/sudoforge/archer/tree/develop
